# Generated by Django 5.1.2 on 2024-10-25 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('classification', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DPCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_half_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('first_half_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('second_half_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('second_half_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization_Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcr_dpcr', models.CharField(choices=[('OPCR', 'OPCR'), ('DPCR', 'DPCR')], default='OPCR', max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcr.division')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitiesDPCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=250)),
                ('first_half_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('first_half_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('second_half_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('second_half_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('narrative', models.CharField(blank=True, max_length=250, null=True)),
                ('evidence_file', models.ImageField(blank=True, null=True, upload_to='evidence/')),
                ('quality', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timeliness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('averagescore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waitallocation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('DPCR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ActivitiesDPCR', to='opcr.dpcr')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ActivitiesDPCR', to='opcr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='OPCR', max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Proposed', 'Proposed'), ('Revised Proposed', 'Revised Proposed'), ('Approved', 'Approved'), ('Revised Approved', 'Revised Approved')], default='Proposed', max_length=20)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcr.division')),
                ('organization_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcr.organization_outcome')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcr.office')),
            ],
        ),
        migrations.CreateModel(
            name='Pillars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Organization_Outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcr.organization_outcome')),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcr.pillars'),
        ),
        migrations.CreateModel(
            name='SmartKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_half_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('first_half_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('second_half_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('second_half_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcr.kpi')),
            ],
        ),
        migrations.CreateModel(
            name='IPCR_OPCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='IPCR/OPCR', max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcr.employee')),
                ('smart_kpi', models.ManyToManyField(to='opcr.smartkpi')),
            ],
        ),
        migrations.AddField(
            model_name='dpcr',
            name='smart_kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcr.smartkpi'),
        ),
        migrations.CreateModel(
            name='ActivitiesOPCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=250)),
                ('first_half_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('first_half_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('second_half_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('second_half_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('narrative', models.CharField(blank=True, max_length=250, null=True)),
                ('evidence_file', models.ImageField(blank=True, null=True, upload_to='evidence/')),
                ('quality', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timeliness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('averagescore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waitallocation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_opcr', to='opcr.employee')),
                ('smart_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_opcr', to='opcr.smartkpi')),
            ],
        ),
    ]
