# Generated by Django 5.1.2 on 2024-10-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0003_alter_activitiesopcr_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesopcr',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_opcr', to='opcr.employee'),
        ),
    ]
