# Generated by Django 5.1.2 on 2024-10-29 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0006_rename_waitallocation_activitiesdpcr_weightallocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitiesdpcr',
            old_name='DPCR',
            new_name='DPCR_kpi',
        ),
    ]
