# Generated by Django 5.1.2 on 2024-10-29 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0007_rename_dpcr_activitiesdpcr_dpcr_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcr_opcr',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opcr.employee'),
        ),
    ]
