# Generated by Django 5.1.2 on 2024-10-29 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0008_alter_ipcr_opcr_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pillar_kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pillars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcr.pillars')),
            ],
        ),
    ]
