# Generated by Django 5.1.2 on 2024-10-29 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0009_pillar_kpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='OPCR', max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Proposed', 'Proposed'), ('Revised Proposed', 'Revised Proposed'), ('Approved', 'Approved'), ('Revised Approved', 'Revised Approved')], default='Proposed', max_length=20)),
                ('Pillar_kpi', models.ManyToManyField(to='opcr.pillar_kpi')),
                ('division', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opcr.division')),
            ],
        ),
    ]
