# Generated by Django 5.1.2 on 2024-10-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0011_opcr_smart_kpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pillars',
            name='Organization_Outcome',
        ),
        migrations.AddField(
            model_name='pillars',
            name='Organization_Outcome',
            field=models.ManyToManyField(to='opcr.organization_outcome'),
        ),
    ]
