# Generated by Django 5.1.2 on 2024-10-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0012_remove_pillars_organization_outcome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcr',
            old_name='Pillar_kpi',
            new_name='pillar_kpi',
        ),
    ]
