# Generated by Django 5.1.2 on 2024-10-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0013_rename_pillar_kpi_opcr_pillar_kpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcr',
            name='pillar_kpi',
        ),
    ]
