# Generated by Django 5.1.2 on 2024-10-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0014_remove_opcr_pillar_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcr',
            name='pillar_kpi',
            field=models.ManyToManyField(to='opcr.pillar_kpi'),
        ),
    ]
