# Generated by Django 5.1.2 on 2024-10-30 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0015_opcr_pillar_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesopcr',
            name='smart_kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_opcr', to='opcr.opcr_smart_kpi'),
        ),
    ]
