# Generated by Django 5.1.2 on 2024-10-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0016_alter_activitiesopcr_smart_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcr_opcr',
            name='smart_kpi',
            field=models.ManyToManyField(to='opcr.opcr_smart_kpi'),
        ),
    ]
