# Generated by Django 5.1.2 on 2024-10-30 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0017_alter_ipcr_opcr_smart_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpcr',
            name='smart_kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcr.opcr_smart_kpi'),
        ),
    ]
