# Generated by Django 5.1.2 on 2024-10-30 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0018_alter_dpcr_smart_kpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCR_DPCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='IPCR/OPCR', max_length=255)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opcr.employee')),
                ('smart_kpi_dpcr', models.ManyToManyField(to='opcr.opcr_smart_kpi')),
            ],
        ),
    ]
