# Generated by Django 5.1.2 on 2024-10-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0019_ipcr_dpcr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcr_dpcr',
            name='name',
            field=models.CharField(default='IPCR/DPCR', max_length=255),
        ),
        migrations.AlterField(
            model_name='ipcr_dpcr',
            name='smart_kpi_dpcr',
            field=models.ManyToManyField(to='opcr.dpcr'),
        ),
    ]
