# Generated by Django 5.1.2 on 2024-10-30 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0022_alter_activitiesopcr_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesopcr',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_opcr', to=settings.AUTH_USER_MODEL),
        ),
    ]
