# Generated by Django 5.1.2 on 2024-11-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0023_alter_activitiesopcr_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='SmartKPI',
        ),
    ]
