# Generated by Django 5.1.2 on 2024-11-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0024_employee_locked_delete_smartkpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesopcr',
            name='head_Remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='activitiesopcr',
            name='status',
            field=models.CharField(blank=True, choices=[('Proposed', 'Proposed'), ('Revised Proposed', 'Revised Proposed'), ('Approved', 'Approved'), ('Revised Approved', 'Revised Approved')], default='', max_length=20, null=True),
        ),
    ]
