# Generated by Django 5.1.2 on 2024-11-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0025_activitiesopcr_head_remarks_activitiesopcr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesdpcr',
            name='head_Remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='activitiesdpcr',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('For Revision', 'To be Revised'), ('Please Delete', 'To be Deleted')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activitiesopcr',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('For Revision', 'To be Revised'), ('Please Delete', 'To be Deleted')], default='', max_length=20, null=True),
        ),
    ]
