# Generated by Django 5.1.2 on 2024-11-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0026_activitiesdpcr_head_remarks_activitiesdpcr_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitiesdpcr',
            old_name='status',
            new_name='dpcr_status',
        ),
        migrations.RenameField(
            model_name='activitiesopcr',
            old_name='status',
            new_name='opcr_status',
        ),
    ]
