# Generated by Django 5.1.2 on 2024-11-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0027_rename_status_activitiesdpcr_dpcr_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitiesdpcr',
            old_name='Remarks',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='activitiesopcr',
            old_name='Remarks',
            new_name='remarks',
        ),
        migrations.AlterField(
            model_name='activitiesdpcr',
            name='dpcr_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('To be Revised', 'To be Revised'), ('To be Deleted', 'To be Delete')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activitiesopcr',
            name='opcr_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('To be Revised', 'To be Revised'), ('To be Deleted', 'To be Delete')], default='', max_length=20, null=True),
        ),
    ]
