# Generated by Django 5.1.2 on 2024-11-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0028_rename_remarks_activitiesdpcr_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitiesdpcr',
            old_name='head_Remarks',
            new_name='head_remarks',
        ),
        migrations.RenameField(
            model_name='activitiesopcr',
            old_name='head_Remarks',
            new_name='head_remarks',
        ),
    ]
