# Generated by Django 5.1.2 on 2024-11-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0029_rename_head_remarks_activitiesdpcr_head_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='category',
            field=models.CharField(blank=True, choices=[('Project', 'Project'), ('Activity', 'Activity'), ('Program', 'Program'), ('Policy', 'Policy')], default='', max_length=20, null=True),
        ),
    ]
