# Generated by Django 5.1.2 on 2024-11-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0030_opcr_smart_kpi_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
