# Generated by Django 5.1.2 on 2024-11-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0032_rename_dpcr_kpi_activitiesdpcr_dpcr_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='averagescore',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='evidence_file',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/'),
        ),
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='first_half_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='first_half_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='narrative',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='quality',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='second_half_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='second_half_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='timeliness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
