# Generated by Django 5.1.2 on 2024-11-25 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0034_opcr_smart_kpi_assignedto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pillars',
            name='Organization_Outcome',
        ),
        migrations.AddField(
            model_name='pillars',
            name='Organization_Outcome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opcr.organization_outcome'),
            preserve_default=False,
        ),
    ]
