# Generated by Django 5.1.2 on 2024-11-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0035_remove_pillars_organization_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcr_smart_kpi',
            name='budget_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
