# Generated by Django 5.1.2 on 2024-11-28 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0037_opcr_smart_kpi_accomplishment_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitiesdpcr',
            name='evidence_file',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('opcr_smart_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='opcr.opcr_smart_kpi')),
            ],
        ),
    ]
