# Generated by Django 5.1.2 on 2024-11-28 07:53

import opcr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0038_remove_activitiesdpcr_evidence_file_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesdpcr',
            name='narrative',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/', validators=[opcr.models.validate_file_extension, opcr.models.validate_file_size]),
        ),
    ]
