# Generated by Django 5.1.2 on 2024-11-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0039_alter_activitiesdpcr_narrative_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesdpcr',
            name='narrative',
            field=models.TextField(blank=True, null=True),
        ),
    ]
