# Generated by Django 5.1.2 on 2024-11-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0040_alter_activitiesdpcr_narrative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesopcr',
            name='narrative',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opcr_smart_kpi',
            name='narrative',
            field=models.TextField(blank=True, null=True),
        ),
    ]
