# Generated by Django 5.1.2 on 2024-12-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0041_alter_activitiesopcr_narrative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
            ],
        ),
    ]
