# Generated by Django 5.1.2 on 2024-12-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0042_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='acronym',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
