# Generated by Django 5.1.2 on 2025-02-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0045_alter_opcr_smart_kpi_first_half_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcr_smart_kpi',
            name='accomplishment_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='opcr_smart_kpi',
            name='accomplishment_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='opcr_smart_kpi',
            name='averagescore',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='opcr_smart_kpi',
            name='efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='opcr_smart_kpi',
            name='quality',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='opcr_smart_kpi',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='opcr_smart_kpi',
            name='timeliness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
