# Generated by Django 5.1.2 on 2025-03-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0046_alter_opcr_smart_kpi_accomplishment_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcr_smart_kpi',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
