# Generated by Django 5.1.2 on 2025-05-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0048_remove_opcr_division_opcr_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcr',
            name='division',
        ),
        migrations.AddField(
            model_name='opcr',
            name='division',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='opcr.division'),
            preserve_default=False,
        ),
    ]
