# Generated by Django 5.1.2 on 2025-05-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcr', '0049_remove_opcr_division_opcr_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='division',
        ),
        migrations.AddField(
            model_name='employee',
            name='division',
            field=models.ManyToManyField(to='opcr.division'),
        ),
    ]
